source 'https://rubygems.org'

# Specify your gem's dependencies in aws_manager.gemspec
gemspec

gem 'extensions'
gem 'aws-sdk', '~> 2.0.45'
gem 'thor', '~> 0.19.1'
gem 'system-getifaddrs', '~> 0.2.1'
gem 'diffy', '~> 3.0.7'
gem 'rspec', '~>3.2.0', require: false, group: :test
gem 'simplecov', '~>0.10.0', require: false, group: :test
gem 'simplecov-rcov', '~>0.2.3', require: false, group: :test
gem 'byebug', '~>8.2.5', require: false, group: :test
